[package]
name = "complider"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
pollster = "0.3.0"
wgpu = { version = "22.1.0", features = ["glsl"] }
winit = { version = "0.29", features = ["rwh_05"] }
